title: Simple Project Homepage
description: A very simple Jekyll layout for Github project
baseurl: "https://errordeveloper.github.io/simple-project-homepage"

font-awesome-include: true # make this false if you don't need font-awesome

exclude: ["README.md"]

repository: errordeveloper/simple-project-homepage

exclude:
  - vendor
  - pkg
  - cmd
